{% set name = "kickstart" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Keats/kickstart/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 5aae308d7d6aa021ddf7f5dc882f8199a5d4f4db8cb8f7175c1c1ac831075a8c

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses

test:
  commands:
    - kickstart --help

about:
  home: https://github.com/Keats/kickstart
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Scaffolding tool to get new projects up and running quickly
  dev_url: https://github.com/Keats/kickstart

extra:
  recipe-maintainers:
    - danielnachun
